version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sayren-backend
    ports:
      - "8801:8080"   # backend 자체 포트
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    restart: always
    networks:
      - sayren-net

  redis:
    image: redis:7.2-alpine
    container_name: sayren-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "8802:6379"
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - sayren-net

networks:
  sayren-net:

volumes:
  redis-data:
