spring:
  application:
    name: sayren_back

  config:
    import:
      - "optional:classpath:secret/db.yml"
      - "optional:classpath:secret/jwt.yml"
      - "optional:classpath:secret/mail.yml"
      - "optional:classpath:secret/next.yml"
      - "optional:classpath:secret/portone.yml"
      - "optional:classpath:secret/solapi.yml"
      - "optional:classpath:secret/oauth.yml"
      - "optional:classpath:secret-prod/oauth.yml"

app:
  backend:
    base-url: "https://api.sayren.imchobo.com"

  frontend:
    base-url: "https://sayren.imchobo.com"

  oauth:
    base-url: "https://api.sayren.imchobo.com"
