spring:
  application:
    name: sayren_back
  config:
    import:
      - optional:classpath:secret/db.yml
      - optional:classpath:secret/jwt.yml
      - optional:classpath:secret/oauth.yml
      - optional:classpath:secret/portone.yml
      - optional:classpath:secret/mail.yml
      - optional:classpath:secret/solapi.yml
      - optional:classpath:secret/redis.yml
      - optional:classpath:secret/next.yml

      - optional:file:/app/secret/db.yml
      - optional:file:/app/secret/jwt.yml
      - optional:file:/app/secret/oauth.yml
      - optional:file:/app/secret/portone.yml
      - optional:file:/app/secret/mail.yml
      - optional:file:/app/secret/solapi.yml
      - optional:file:/app/secret/redis.yml
      - optional:file:/app/secret/next.yml
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: true

logging:
  level:
    org.springframework.security: DEBUG
